# Movie Success Prediction - Data Cleaning

This notebook performs data loading, merging, cleaning, and preprocessing for the movie success prediction project using the TMDB dataset.

Steps:
- Load datasets
- Merge movies and credits
- Clean and preprocess data
- Extract useful features (genres, cast, director)
- Handle missing values
- Create target variable (success)
- Save cleaned dataset

In [1]:
import pandas as pd
import ast
import os

movies_path = "../Datasets/tmdb_5000_movies.csv"
credits_path = "../Datasets/tmdb_5000_credits.csv"

movies = pd.read_csv(movies_path)
credits = pd.read_csv(credits_path)

print("Movies shape:", movies.shape)
print("Credits shape:", credits.shape)

display(movies.head())
display(credits.head())

Movies shape: (4803, 20)
Credits shape: (4803, 4)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [2]:
print("Movies columns:")
print(movies.columns.tolist())

print("\nCredits columns:")
print(credits.columns.tolist())

Movies columns:
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

Credits columns:
['movie_id', 'title', 'cast', 'crew']

In [3]:
credits = credits.rename(columns={"movie_id": "id"})
df = movies.merge(credits, on="id", suffixes=("_movie", "_credit"))

print("Merged shape:", df.shape)
print(df.columns.tolist())
display(df.head())

Merged shape: (4803, 23)
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title_movie', 'vote_average', 'vote_count', 'title_credit', 'cast', 'crew']

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_movie,vote_average,vote_count,title_credit,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
if "title_movie" in df.columns:
    df = df.rename(columns={"title_movie": "title"})
elif "original_title" in df.columns:
    df = df.rename(columns={"original_title": "title"})

if "title_credit" in df.columns:
    df = df.drop(columns=["title_credit"])

print(df.columns.tolist())

['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'cast', 'crew']

In [5]:
columns_needed = [
    "id",
    "title",
    "genres",
    "keywords",
    "cast",
    "crew",
    "budget",
    "revenue",
    "runtime",
    "vote_average",
    "vote_count",
    "popularity",
    "release_date",
    "original_language"
]

df = df[columns_needed].copy()

display(df.head())

,id,title,genres,keywords,cast,crew,budget,revenue,runtime,vote_average,vote_count,popularity,release_date,original_language
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,2787965087,162.0,7.2,11800,150.437577,2009-12-10,en
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",300000000,961000000,169.0,6.9,4500,139.082615,2007-05-19,en
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",245000000,880674609,148.0,6.3,4466,107.376788,2015-10-26,en
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",250000000,1084939099,165.0,7.6,9106,112.312950,2012-07-16,en
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",260000000,284139100,132.0,6.1,2124,43.926995,2012-03-07,en

In [6]:
def safe_parse(text):
    """
    Converts a string version of a list/dictionary into a Python object.
    Returns an empty list if parsing fails.
    """
    try:
        return ast.literal_eval(text)
    except:
        return []


def extract_names(text):
    """
    Extracts the 'name' values from JSON-like list columns.
    Used for genres and keywords.
    """
    items = safe_parse(text)
    names = []
    
    for item in items:
        if isinstance(item, dict) and "name" in item:
            names.append(item["name"])
    
    return names


def extract_top_cast(text, top_n=3):
    """
    Extracts the first top_n cast member names.
    """
    items = safe_parse(text)
    names = []
    
    for item in items:
        if isinstance(item, dict) and "name" in item:
            names.append(item["name"])
        
        if len(names) == top_n:
            break
    
    return names


def extract_director(text):
    """
    Extracts the director name from the crew column.
    """
    items = safe_parse(text)
    
    for item in items:
        if isinstance(item, dict) and item.get("job") == "Director":
            return item.get("name")
    
    return None

In [7]:
df.loc[:, "genres"] = df["genres"].apply(extract_names)
df.loc[:, "keywords"] = df["keywords"].apply(extract_names)
df.loc[:, "cast"] = df["cast"].apply(extract_top_cast)
df.loc[:, "director"] = df["crew"].apply(extract_director)

df = df.drop(columns=["crew"])

display(df[["title", "genres", "keywords", "cast", "director"]].head())

,title,genres,keywords,cast,director
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton

In [8]:
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
id                    0
title                 0
genres                0
keywords              0
cast                  0
budget                0
revenue               0
runtime               2
vote_average          0
vote_count            0
popularity            0
release_date          1
original_language     0
director             30
dtype: int64

In [9]:
# Runtime has very few missing values, so we can fill it with the median.
df.loc[:, "runtime"] = df["runtime"].fillna(df["runtime"].median())

# Release date has very few missing values, so we remove those rows.
df = df.dropna(subset=["release_date", "director"]).copy()

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
id                   0
title                0
genres               0
keywords             0
cast                 0
budget               0
revenue              0
runtime              0
vote_average         0
vote_count           0
popularity           0
release_date         0
original_language    0
director             0
dtype: int64

In [10]:
print("Rows before removing zero budget/revenue:", df.shape[0])

df = df[(df["budget"] > 0) & (df["revenue"] > 0)].copy()

print("Rows after removing zero budget/revenue:", df.shape[0])

Rows before removing zero budget/revenue: 4773
Rows after removing zero budget/revenue: 3227

In [11]:
# Convert release_date to datetime safely
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")

# Remove rows where release_date could not be converted
df = df.dropna(subset=["release_date"]).copy()

# Create release year
df["release_year"] = pd.DatetimeIndex(df["release_date"]).year

display(df[["title", "release_date", "release_year"]].head())

                                      title release_date  release_year
0                                    Avatar   2009-12-10          2009
1  Pirates of the Caribbean: At World's End   2007-05-19          2007
2                                   Spectre   2015-10-26          2015
3                     The Dark Knight Rises   2012-07-16          2012
4                               John Carter   2012-03-07          2012

In [12]:
df.loc[:, "success"] = df["revenue"] > df["budget"]

display(df[["title", "budget", "revenue", "success"]].head())

                                      title     budget     revenue  success
0                                    Avatar  237000000  2787965087     True
1  Pirates of the Caribbean: At World's End  300000000   961000000     True
2                                   Spectre  245000000   880674609     True
3                     The Dark Knight Rises  250000000  1084939099     True
4                               John Carter  260000000   284139100     True

In [13]:
df.loc[:, "profit"] = df["revenue"] - df["budget"]
df.loc[:, "roi"] = df["profit"] / df["budget"]

df.loc[:, "main_genre"] = df["genres"].apply(lambda x: x[0] if len(x) > 0 else "Unknown")
df.loc[:, "main_actor"] = df["cast"].apply(lambda x: x[0] if len(x) > 0 else "Unknown")

display(df[["title", "main_genre", "main_actor", "director", "profit", "roi"]].head())

,title,main_genre,main_actor,director,profit,roi
0,Avatar,Action,Sam Worthington,James Cameron,2550965087,10.763566
1,Pirates of the Caribbean: At World's End,Adventure,Johnny Depp,Gore Verbinski,661000000,2.203333
2,Spectre,Action,Daniel Craig,Sam Mendes,635674609,2.594590
3,The Dark Knight Rises,Action,Christian Bale,Christopher Nolan,834939099,3.339756
4,John Carter,Action,Taylor Kitsch,Andrew Stanton,24139100,0.092843

In [14]:
print("Final cleaned dataset shape:", df.shape)
print("\nFinal columns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

display(df.head())

Final cleaned dataset shape: (3227, 20)

Final columns:
['id', 'title', 'genres', 'keywords', 'cast', 'budget', 'revenue', 'runtime', 'vote_average', 'vote_count', 'popularity', 'release_date', 'original_language', 'director', 'release_year', 'success', 'profit', 'roi', 'main_genre', 'main_actor']

Data types:
id                            int64
title                        object
genres                       object
keywords                     object
cast                         object
budget                        int64
revenue                       int64
runtime                     float64
vote_average                float64
vote_count                    int64
popularity                  float64
release_date         datetime64[ns]
original_language            object
director                     object
release_year                  int32
success                        bool
profit                        int64
roi                         float64
main_genre                   object
main_actor                   object
dtype: object

,id,title,genres,keywords,cast,budget,revenue,runtime,vote_average,vote_count,popularity,release_date,original_language,director,release_year,success,profit,roi,main_genre,main_actor
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",237000000,2787965087,162.0,7.2,11800,150.437577,2009-12-10,en,James Cameron,2009,True,2550965087,10.763566,Action,Sam Worthington
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",300000000,961000000,169.0,6.9,4500,139.082615,2007-05-19,en,Gore Verbinski,2007,True,661000000,2.203333,Adventure,Johnny Depp
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",245000000,880674609,148.0,6.3,4466,107.376788,2015-10-26,en,Sam Mendes,2015,True,635674609,2.594590,Action,Daniel Craig
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",250000000,1084939099,165.0,7.6,9106,112.312950,2012-07-16,en,Christopher Nolan,2012,True,834939099,3.339756,Action,Christian Bale
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",260000000,284139100,132.0,6.1,2124,43.926995,2012-03-07,en,Andrew Stanton,2012,True,24139100,0.092843,Action,Taylor Kitsch

In [15]:
df.to_csv("../Datasets/clean_movies.csv", index=False)

print("Saved clean_movies.csv successfully!")

print("\nFiles in current folder:")
print(os.listdir())

Saved clean_movies.csv successfully!

Files in current folder:
['sql_database.ipynb', 'data_cleaning.ipynb', 'visualization.ipynb', '.ipynb_checkpoints']

In [16]:
df.shape

(3227, 20)

In [17]:
df.columns

Index(['id', 'title', 'genres', 'keywords', 'cast', 'budget', 'revenue',
       'runtime', 'vote_average', 'vote_count', 'popularity', 'release_date',
       'original_language', 'director', 'release_year', 'success', 'profit',
       'roi', 'main_genre', 'main_actor'],
      dtype='object')

In [18]:
df.isnull().sum()

id                   0
title                0
genres               0
keywords             0
cast                 0
budget               0
revenue              0
runtime              0
vote_average         0
vote_count           0
popularity           0
release_date         0
original_language    0
director             0
release_year         0
success              0
profit               0
roi                  0
main_genre           0
main_actor           0
dtype: int64

In [19]:
df.head()

,id,title,genres,keywords,cast,budget,revenue,runtime,vote_average,vote_count,popularity,release_date,original_language,director,release_year,success,profit,roi,main_genre,main_actor
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",237000000,2787965087,162.0,7.2,11800,150.437577,2009-12-10,en,James Cameron,2009,True,2550965087,10.763566,Action,Sam Worthington
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",300000000,961000000,169.0,6.9,4500,139.082615,2007-05-19,en,Gore Verbinski,2007,True,661000000,2.203333,Adventure,Johnny Depp
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",245000000,880674609,148.0,6.3,4466,107.376788,2015-10-26,en,Sam Mendes,2015,True,635674609,2.594590,Action,Daniel Craig
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",250000000,1084939099,165.0,7.6,9106,112.312950,2012-07-16,en,Christopher Nolan,2012,True,834939099,3.339756,Action,Christian Bale
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",260000000,284139100,132.0,6.1,2124,43.926995,2012-03-07,en,Andrew Stanton,2012,True,24139100,0.092843,Action,Taylor Kitsch